### ISSUE TITLE
How to visualize during Training?

### ISSUE THREAD

**Issue by erdisayar** [Stilwell-Git/Hindsight-Goal-Generation#2]
Hi.

How can I see the Mujoco environment during the training?

**Comment by Stilwell-Git** [comment]
The visualization is supported by `env.render()`.

**Comment by erdisayar** [comment]
I added it like this
in hgg.py under the function `def learn()` and under the for loop `for timestep in range(args.timesteps):`
`self.env_List[i].render()`

A black screen pops up and gives error "Creating window glfw
ERROR: GLEW initalization error: Missing GL version" . However, when I try to run other gym environment with `env.render()`, the mujoco simulation runs without any problem

**Comment by Stilwell-Git** [comment]
I cannot reproduce this issue in my Python environment.
Of course, our `env` instance only takes a wrapper based on a standard gym environment.
Please refer to the following code:
https://github.com/Stilwell-Git/Hindsight-Goal-Generation/blob/3abd832bcd484da62dcbc72296f9435a3d55397d/envs/fetch/vanilla.py#L26
Using the same Python configuration, you should open the render as other gym environments.

**Comment by Rixtho** [comment]
@erdisayar Could you maybe share how you solved this?

**Comment by erdisayar** [comment]
Hi, @Rixtho , If you have the above error I mentioned, then you need to add these lines in your `.bashrc`

For example;
`LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/erdi/.mujoco/mujoco210/bin:/usr/lib/nvidia`
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so`

**Comment by Rixtho** [comment]
I still get the same error after setting these environment variables, but no black screen. Where did you add the render statement?

**Comment by erdisayar** [comment]
`self.env_List[i].render()` add this after this line
https://github.com/Stilwell-Git/Hindsight-Goal-Generation/blob/master/learner/hgg.py#L175

**Comment by Rixtho** [comment]
Had to fix some driver issues as well but it's working now. Thanks for the help!
